"""Static mapping data for units and counters."""
from __future__ import annotations

UNIT_LINE_MAP = {
    # Economy
    "Villager": "villager",
    "Fishing Ship": "fishing_ship",
    "Trade Cart": "trade",
    "Trade Cog": "trade",
    # Infantry
    "Militia": "militia_line",
    "Man-at-Arms": "militia_line",
    "Long Swordsman": "militia_line",
    "Two-Handed Swordsman": "militia_line",
    "Champion": "militia_line",
    "Spearman": "spear_line",
    "Pikeman": "spear_line",
    "Halberdier": "spear_line",
    "Eagle Scout": "eagle_line",
    "Eagle Warrior": "eagle_line",
    "Elite Eagle Warrior": "eagle_line",
    "Condottiero": "militia_line",
    "Huskarl": "militia_line",
    "Elite Huskarl": "militia_line",
    "Kamayuk": "spear_line",
    "Elite Kamayuk": "spear_line",
    "Samurai": "militia_line",
    "Elite Samurai": "militia_line",
    "Berserk": "militia_line",
    "Elite Berserk": "militia_line",
    "Teutonic Knight": "militia_line",
    "Elite Teutonic Knight": "militia_line",
    "Jaguar Warrior": "militia_line",
    "Elite Jaguar Warrior": "militia_line",
    "Woad Raider": "militia_line",
    "Elite Woad Raider": "militia_line",
    "Karambit Warrior": "militia_line",
    "Elite Karambit Warrior": "militia_line",
    "Obuch": "militia_line",
    "Elite Obuch": "militia_line",
    # Archers
    "Archer": "archer_line",
    "Crossbowman": "archer_line",
    "Arbalester": "archer_line",
    "Skirmisher": "skirm_line",
    "Elite Skirmisher": "skirm_line",
    "Imperial Skirmisher": "skirm_line",
    "Cavalry Archer": "cav_archer_line",
    "Heavy Cavalry Archer": "cav_archer_line",
    "Hand Cannoneer": "gunpowder",
    "Longbowman": "archer_line",
    "Elite Longbowman": "archer_line",
    "Chu Ko Nu": "archer_line",
    "Elite Chu Ko Nu": "archer_line",
    "Plumed Archer": "archer_line",
    "Elite Plumed Archer": "archer_line",
    "Rattan Archer": "archer_line",
    "Elite Rattan Archer": "archer_line",
    "Arambai": "cav_archer_line",
    "Elite Arambai": "cav_archer_line",
    "Mangudai": "cav_archer_line",
    "Elite Mangudai": "cav_archer_line",
    "Conquistador": "cav_archer_line",
    "Elite Conquistador": "cav_archer_line",
    "War Wagon": "cav_archer_line",
    "Elite War Wagon": "cav_archer_line",
    "Slinger": "archer_line",
    "Skirmisher": "skirm_line",
    "Genitour": "skirm_line",
    "Elite Genitour": "skirm_line",
    # Cavalry
    "Scout Cavalry": "scout_cav_line",
    "Light Cavalry": "scout_cav_line",
    "Hussar": "scout_cav_line",
    "Winged Hussar": "scout_cav_line",
    "Knight": "knight_line",
    "Cavalier": "knight_line",
    "Paladin": "knight_line",
    "Camel Rider": "camel_line",
    "Heavy Camel Rider": "camel_line",
    "Imperial Camel Rider": "camel_line",
    "Battle Elephant": "elephant_line",
    "Elite Battle Elephant": "elephant_line",
    "War Elephant": "elephant_line",
    "Elite War Elephant": "elephant_line",
    "Steppe Lancer": "knight_line",
    "Elite Steppe Lancer": "knight_line",
    "Boyar": "knight_line",
    "Elite Boyar": "knight_line",
    "Cataphract": "knight_line",
    "Elite Cataphract": "knight_line",
    "Konnik": "knight_line",
    "Elite Konnik": "knight_line",
    "Leitis": "knight_line",
    "Elite Leitis": "knight_line",
    "Keshik": "knight_line",
    "Elite Keshik": "knight_line",
    "Magyar Huszar": "scout_cav_line",
    "Elite Magyar Huszar": "scout_cav_line",
    "Tarkan": "knight_line",
    "Elite Tarkan": "knight_line",
    "Coustillier": "knight_line",
    "Elite Coustillier": "knight_line",
    "Shrivamsha Rider": "knight_line",
    "Elite Shrivamsha Rider": "knight_line",
    # Monks
    "Monk": "monk",
    "Missionary": "monk",
    # Siege
    "Mangonel": "siege",
    "Onager": "siege",
    "Siege Onager": "siege",
    "Scorpion": "siege",
    "Heavy Scorpion": "siege",
    "Battering Ram": "siege",
    "Capped Ram": "siege",
    "Siege Ram": "siege",
    "Siege Tower": "siege",
    "Bombard Cannon": "siege",
    "Houfnice": "siege",
    "Organ Gun": "gunpowder",
    "Elite Organ Gun": "gunpowder",
    "Torsion Engines": "siege",
    # Gunpowder/unique gunpowder
    "Janissary": "gunpowder",
    "Elite Janissary": "gunpowder",
    "Conquistador": "cav_archer_line",
    "Elite Conquistador": "cav_archer_line",
    "Hand Cannoneer": "gunpowder",
    "Bombard Cannon": "siege",
    # Navy
    "Galley": "navy",
    "War Galley": "navy",
    "Galleon": "navy",
    "Fire Galley": "navy",
    "Fire Ship": "navy",
    "Fast Fire Ship": "navy",
    "Demolition Raft": "navy",
    "Demolition Ship": "navy",
    "Heavy Demolition Ship": "navy",
    "Cannon Galleon": "navy",
    "Elite Cannon Galleon": "navy",
    "Dromon": "navy",
    "Longboat": "navy",
    "Elite Longboat": "navy",
    "Turtle Ship": "navy",
    "Elite Turtle Ship": "navy",
    "Caravel": "navy",
    "Elite Caravel": "navy",
    "Thirisadai": "navy",
    # Unique units mapped to line behavior
    "Throwing Axeman": "militia_line",
    "Elite Throwing Axeman": "militia_line",
    "Warrior Priest": "militia_line",
    "Elite Warrior Priest": "militia_line",
    "Gbeto": "militia_line",
    "Elite Gbeto": "militia_line",
    "Shotel Warrior": "militia_line",
    "Elite Shotel Warrior": "militia_line",
    "Serjeant": "militia_line",
    "Elite Serjeant": "militia_line",
    "Urumi Swordsman": "militia_line",
    "Elite Urumi Swordsman": "militia_line",
    "Ratha": "cav_archer_line",
    "Elite Ratha": "cav_archer_line",
    "Ghulam": "militia_line",
    "Elite Ghulam": "militia_line",
    "Tarkan": "knight_line",
    "Elite Tarkan": "knight_line",
    "Kipchak": "cav_archer_line",
    "Elite Kipchak": "cav_archer_line",
    "Leitis": "knight_line",
    "Elite Leitis": "knight_line",
    "Chakram Thrower": "archer_line",
    "Elite Chakram Thrower": "archer_line",
    "Camel Archer": "cav_archer_line",
    "Elite Camel Archer": "cav_archer_line",
    "Rattan Archer": "archer_line",
    "Elite Rattan Archer": "archer_line",
    "Ballista Elephant": "siege",
    "Elite Ballista Elephant": "siege",
    "Armored Elephant": "siege",
    "Siege Elephant": "siege",
}

TECH_CATEGORIES = {
    "Loom": "eco",
    "Double-Bit Axe": "eco",
    "Horse Collar": "eco",
    "Wheelbarrow": "eco",
    "Hand Cart": "eco",
    "Heavy Plow": "eco",
    "Two-Man Saw": "eco",
    "Gold Mining": "eco",
    "Gold Shaft Mining": "eco",
    "Stone Mining": "eco",
    "Stone Shaft Mining": "eco",
    "Town Watch": "eco",
    "Town Patrol": "eco",
    "Wheelbarrow": "eco",
    "Crop Rotation": "eco",
    "Gillnets": "eco",
    "Careening": "eco",
    "Dry Dock": "eco",
    "Shipwright": "eco",
    "Fletching": "military",
    "Bodkin Arrow": "military",
    "Bracer": "military",
    "Thumb Ring": "military",
    "Parthian Tactics": "military",
    "Leather Archer Armor": "military",
    "Ring Archer Armor": "military",
    "Scale Mail Armor": "military",
    "Chain Mail Armor": "military",
    "Plate Mail Armor": "military",
    "Scale Barding Armor": "military",
    "Chain Barding Armor": "military",
    "Plate Barding Armor": "military",
    "Forging": "military",
    "Iron Casting": "military",
    "Blast Furnace": "military",
    "Pikeman": "military",
    "Halberdier": "military",
    "Squires": "military",
    "Supplies": "military",
    "Arson": "military",
    "Bloodlines": "military",
    "Husbandry": "military",
    "Redemption": "military",
    "Sanctity": "military",
    "Fervor": "military",
    "Atonement": "military",
    "Heresy": "military",
    "Faith": "military",
    "Chemistry": "military",
    "Siege Engineers": "military",
    "Conscription": "military",
    "Hoardings": "military",
    "Sappers": "military",
}

COUNTER_MAP = {
    "knight_line": ["spear_line", "camel_line", "monk"],
    "scout_cav_line": ["spear_line", "monk"],
    "camel_line": ["spear_line", "monk"],
    "archer_line": ["skirm_line"],
    "skirm_line": ["scout_cav_line", "militia_line"],
    "spear_line": ["archer_line"],
    "militia_line": ["archer_line"],
    "cav_archer_line": ["skirm_line", "scout_cav_line"],
    "siege": ["scout_cav_line", "monk"],
    "gunpowder": ["skirm_line", "scout_cav_line"],
    "eagle_line": ["militia_line", "archer_line"],
    "elephant_line": ["monk", "spear_line"],
}

GOLD_LINES = {
    "archer_line",
    "knight_line",
    "camel_line",
    "cav_archer_line",
    "siege",
    "monk",
    "gunpowder",
    "elephant_line",
    "militia_line",
    "eagle_line",
    "navy",
}

TRASH_LINES = {"skirm_line", "spear_line"}

PRODUCTION_BUILDINGS = {
    "Barracks",
    "Archery Range",
    "Stable",
    "Siege Workshop",
    "Dock",
    "Castle",
    "Monastery",
}

BUILDING_KEYS = {
    "Barracks": "barracks",
    "Archery Range": "archery_range",
    "Stable": "stable",
    "Blacksmith": "blacksmith",
    "Market": "market",
    "Monastery": "monastery",
    "University": "university",
    "Siege Workshop": "siege_workshop",
    "Dock": "dock",
    "Castle": "castle",
    "Town Center": "town_center",
}
